### ISSUE TITLE
fontend issue: Error: EACCES: permission denied, mkdir '/app/node_modules/.vite/deps_temp_18b14f38'

### ISSUE THREAD

**Issue by ThanhHung2112** [lucastononro/llm-food-delivery#6]
```bash
frontend-1  | 
frontend-1  |   VITE v4.5.2  ready in 290 ms
frontend-1  | 
frontend-1  |   ➜  Local:   http://localhost:5173/
frontend-1  |   ➜  Network: http://172.18.0.2:5173/
frontend-1  | Error: EACCES: permission denied, mkdir '/app/node_modules/.vite/deps_temp_18b14f38'
frontend-1  |     at Object.mkdirSync (node:fs:1386:3)
frontend-1  |     at runOptimizeDeps (file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45821:10)
frontend-1  |     at file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45202:46
frontend-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
backend-1   | Skipping virtualenv creation, as specified in config file.
backend-1   | INFO:     Will watch for changes in these directories: ['/app']
backend-1   | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
backend-1   | INFO:     Started reloader process [1] using StatReload
backend-1   | INFO:     Started server process [21]
backend-1   | INFO:     Waiting for application startup.
backend-1   | INFO:     Application startup complete.
frontend-1  | Assets in public directory cannot be imported from JavaScript.
frontend-1  | If you intend to import that asset, put the file in the src directory, and use /src/shopping-cart-icon.png instead of /src/assets/shopping-cart-icon.png.
frontend-1  | If you intend to use the URL of that asset, use /shopping-cart-icon.png?url.
frontend-1  | Assets in public directory cannot be imported from JavaScript.
frontend-1  | If you intend to import that asset, put the file in the src directory, and use /src/favicon.png instead of /src/assets/favicon.png.
frontend-1  | If you intend to use the URL of that asset, use /favicon.png?url.
frontend-1  | Assets in public directory cannot be imported from JavaScript.
frontend-1  | If you intend to import that asset, put the file in the src directory, and use /src/handsfree.svg instead of /src/assets/handsfree.svg.
frontend-1  | If you intend to use the URL of that asset, use /handsfree.svg?url.
frontend-1  | 4:06:47 AM [vite] error while updating dependencies:
frontend-1  | Error: EACCES: permission denied, mkdir '/app/node_modules/.vite/deps_temp_bd489edc'
frontend-1  |     at Object.mkdirSync (node:fs:1386:3)
frontend-1  |     at runOptimizeDeps (file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45821:10)
frontend-1  |     at runOptimizer (file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45267:38)
frontend-1  |     at rerun (file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45400:9)
frontend-1  |     at Timeout._onTimeout (file:///app/node_modules/vite/dist/node/chunks/dep-52909643.js:45470:17)
frontend-1  |     at listOnTimeout (node:internal/timers:559:17)
frontend-1  |     at processTimers (node:internal/timers:502:7)
```

I'm getting this issue while running your repo. Anyone know how to solve this ?

**Comment by lucastononro** [comment]
Any chance you are running in a corporate computer?

**Comment by ThanhHung2112** [comment]
This have been solve by directly FE and BE then build docker in these folder :v
